using HantahaAPI.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace HantahaAPI.Data.Seeds
{
    public class CountrySeed : IEntityTypeConfiguration<Country>
    {

        public void Configure(EntityTypeBuilder<Country> builder)
        {
            builder.HasData(
                    new Country { Id = 1, Name = "Ascension Adası", EnglishName = "Ascension Island", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AC.svg" },
                    new Country { Id = 2, Name = "Andorra", EnglishName = "Andorra", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg" },
                    new Country { Id = 3, Name = "Birleşik Arap Emirlikleri", EnglishName = "United Arab Emirates", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg" },
                    new Country { Id = 4, Name = "Afganistan", EnglishName = "Afghanistan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg" },
                    new Country { Id = 5, Name = "Antigua ve Barbuda", EnglishName = "Antigua & Barbuda", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg" },
                    new Country { Id = 6, Name = "Anguilla", EnglishName = "Anguilla", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg" },
                    new Country { Id = 7, Name = "Arnavutluk", EnglishName = "Albania", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg" },
                    new Country { Id = 8, Name = "Ermenistan", EnglishName = "Armenia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg" },
                    new Country { Id = 9, Name = "Angola", EnglishName = "Angola", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg" },
                    new Country { Id = 10, Name = "Antarktika", EnglishName = "Antarctica", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg" },
                    new Country { Id = 11, Name = "Arjantin", EnglishName = "Argentina", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg" },
                    new Country { Id = 12, Name = "Amerikan Samoası", EnglishName = "American Samoa", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg" },
                    new Country { Id = 13, Name = "Avusturya", EnglishName = "Austria", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg" },
                    new Country { Id = 14, Name = "Avustralya", EnglishName = "Australia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg" },
                    new Country { Id = 15, Name = "Aruba", EnglishName = "Aruba", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg" },
                    new Country { Id = 16, Name = "Åland Adaları", EnglishName = "Åland Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AX.svg" },
                    new Country { Id = 17, Name = "Azerbaycan", EnglishName = "Azerbaijan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg" },
                    new Country { Id = 18, Name = "Bosna-Hersek", EnglishName = "Bosnia & Herzegovina", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg" },
                    new Country { Id = 19, Name = "Barbados", EnglishName = "Barbados", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg" },
                    new Country { Id = 20, Name = "Bangladeş", EnglishName = "Bangladesh", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg" },
                    new Country { Id = 21, Name = "Belçika", EnglishName = "Belgium", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg" },
                    new Country { Id = 22, Name = "Burkina Faso", EnglishName = "Burkina Faso", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg" },
                    new Country { Id = 23, Name = "Bulgaristan", EnglishName = "Bulgaria", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg" },
                    new Country { Id = 24, Name = "Bahreyn", EnglishName = "Bahrain", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg" },
                    new Country { Id = 25, Name = "Burundi", EnglishName = "Burundi", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg" },
                    new Country { Id = 26, Name = "Benin", EnglishName = "Benin", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg" },
                    new Country { Id = 27, Name = "St. Barthélemy", EnglishName = "St. Barthélemy", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BL.svg" },
                    new Country { Id = 28, Name = "Bermuda", EnglishName = "Bermuda", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg" },
                    new Country { Id = 29, Name = "Brunei", EnglishName = "Brunei", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg" },
                    new Country { Id = 30, Name = "Bolivya", EnglishName = "Bolivia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg" },
                    new Country { Id = 31, Name = "Karayip Hollanda", EnglishName = "Caribbean Netherlands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BQ.svg" },
                    new Country { Id = 32, Name = "Bahamalar", EnglishName = "Bahamas", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg" },
                    new Country { Id = 33, Name = "Butan", EnglishName = "Bhutan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg" },
                    new Country { Id = 34, Name = "Botsvana", EnglishName = "Botswana", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg" },
                    new Country { Id = 35, Name = "Beyaz Rusya", EnglishName = "Belarus", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg" },
                    new Country { Id = 36, Name = "Belize", EnglishName = "Belize", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg" },
                    new Country { Id = 37, Name = "Kanada", EnglishName = "Canada", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg" },
                    new Country { Id = 38, Name = "Cocos (Keeling) Adaları", EnglishName = "Cocos (Keeling) Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg" },
                    new Country { Id = 39, Name = "Kongo - Kinshasa", EnglishName = "Congo - Kinshasa", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg" },
                    new Country { Id = 40, Name = "Orta Afrika Cumhuriyeti", EnglishName = "Central African Republic", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg" },
                    new Country { Id = 41, Name = "Kongo - Brazzaville", EnglishName = "Congo - Brazzaville", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg" },
                    new Country { Id = 42, Name = "İsviçre", EnglishName = "Switzerland", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg" },
                    new Country { Id = 43, Name = "Fildişi Sahili", EnglishName = "Côte d’Ivoire", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg" },
                    new Country { Id = 44, Name = "Cook Adaları", EnglishName = "Cook Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg" },
                    new Country { Id = 45, Name = "Şili", EnglishName = "Chile", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg" },
                    new Country { Id = 46, Name = "Kamerun", EnglishName = "Cameroon", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg" },
                    new Country { Id = 47, Name = "Çin", EnglishName = "China", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg" },
                    new Country { Id = 48, Name = "Kolombiya", EnglishName = "Colombia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg" },
                    new Country { Id = 49, Name = "Kosta Rika", EnglishName = "Costa Rica", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg" },
                    new Country { Id = 50, Name = "Küba", EnglishName = "Cuba", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg" },
                    new Country { Id = 51, Name = "Cape Verde", EnglishName = "Cape Verde", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg" },
                    new Country { Id = 52, Name = "Curaçao", EnglishName = "Curaçao", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg" },
                    new Country { Id = 53, Name = "Christmas Adası", EnglishName = "Christmas Island", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg" },
                    new Country { Id = 54, Name = "Kıbrıs", EnglishName = "Cyprus", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg" },
                    new Country { Id = 55, Name = "Çekya", EnglishName = "Czechia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg" },
                    new Country { Id = 56, Name = "Almanya", EnglishName = "Germany", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg" },
                    new Country { Id = 57, Name = "Cibuti", EnglishName = "Djibouti", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg" },
                    new Country { Id = 58, Name = "Dominika", EnglishName = "Dominica", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg" },
                    new Country { Id = 59, Name = "Dominik Cumhuriyeti", EnglishName = "Dominican Republic", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg" },
                    new Country { Id = 60, Name = "Cezayir", EnglishName = "Algeria", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg" },
                    new Country { Id = 61, Name = "Ekvador", EnglishName = "Ecuador", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg" },
                    new Country { Id = 62, Name = "Mısır", EnglishName = "Egypt", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg" },
                    new Country { Id = 63, Name = "Batı Sahra", EnglishName = "Western Sahara", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EH.svg" },
                    new Country { Id = 64, Name = "Eritre", EnglishName = "Eritrea", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg" },
                    new Country { Id = 65, Name = "Endonezya", EnglishName = "Indonesia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg" },
                    new Country { Id = 66, Name = "Hindistan", EnglishName = "India", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg" },
                    new Country { Id = 67, Name = "Brezilya", EnglishName = "Brazil", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg" },
                    new Country { Id = 68, Name = "İran", EnglishName = "Iran", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg" },
                    new Country { Id = 69, Name = "Irak", EnglishName = "Iraq", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg" },
                    new Country { Id = 70, Name = "İrlanda", EnglishName = "Ireland", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg" },
                    new Country { Id = 71, Name = "Man Adası", EnglishName = "Isle of Man", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg" },
                    new Country { Id = 72, Name = "İzlanda", EnglishName = "Iceland", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg" },
                    new Country { Id = 73, Name = "Italya", EnglishName = "Italy", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg" },
                    new Country { Id = 74, Name = "Jersey", EnglishName = "Jersey", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg" },
                    new Country { Id = 75, Name = "Jamaika", EnglishName = "Jamaica", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg" },
                    new Country { Id = 76, Name = "Ürdün", EnglishName = "Jordan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg" },
                    new Country { Id = 77, Name = "Japonya", EnglishName = "Japan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg" },
                    new Country { Id = 78, Name = "Kenya", EnglishName = "Kenya", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg" },
                    new Country { Id = 79, Name = "Kırgızistan", EnglishName = "Kyrgyzstan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg" },
                    new Country { Id = 80, Name = "Kamboçya", EnglishName = "Cambodia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg" },
                    new Country { Id = 81, Name = "Kiribati", EnglishName = "Kiribati", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg" },
                    new Country { Id = 82, Name = "Komorlar", EnglishName = "Comoros", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg" },
                    new Country { Id = 83, Name = "Saint Kitts ve Nevis", EnglishName = "Saint Kitts and Nevis", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg" },
                    new Country { Id = 84, Name = "Kuzey Kore", EnglishName = "North Korea", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg" },
                    new Country { Id = 85, Name = "Güney Kore", EnglishName = "South Korea", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg" },
                    new Country { Id = 86, Name = "Kuveyt", EnglishName = "Kuwait", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg" },
                    new Country { Id = 87, Name = "Kazakistan", EnglishName = "Kazakhstan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg" },
                    new Country { Id = 88, Name = "Laos", EnglishName = "Laos", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg" },
                    new Country { Id = 89, Name = "Lübnan", EnglishName = "Lebanon", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg" },
                    new Country { Id = 90, Name = "Saint Lucia", EnglishName = "Saint Lucia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg" },
                    new Country { Id = 91, Name = "Liechtenstein", EnglishName = "Liechtenstein", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg" },
                    new Country { Id = 92, Name = "Sri Lanka", EnglishName = "Sri Lanka", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg" },
                    new Country { Id = 93, Name = "Liberya", EnglishName = "Liberia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg" },
                    new Country { Id = 94, Name = "Lesotho", EnglishName = "Lesotho", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg" },
                    new Country { Id = 95, Name = "Litvanya", EnglishName = "Lithuania", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg" },
                    new Country { Id = 96, Name = "Lüksemburg", EnglishName = "Luxembourg", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg" },
                    new Country { Id = 97, Name = "Letonya", EnglishName = "Latvia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg" },
                    new Country { Id = 98, Name = "Libya", EnglishName = "Libya", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg" },
                    new Country { Id = 99, Name = "Fas", EnglishName = "Morocco", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg" },
                    new Country { Id = 100, Name = "Monako", EnglishName = "Monaco", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg" },
                    new Country { Id = 101, Name = "Moldova", EnglishName = "Moldova", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg" },
                    new Country { Id = 102, Name = "Karadağ", EnglishName = "Montenegro", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg" },
                    new Country { Id = 103, Name = "Madagaskar", EnglishName = "Madagascar", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg" },
                    new Country { Id = 104, Name = "Marshall Adaları", EnglishName = "Marshall Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg" },
                    new Country { Id = 105, Name = "Makedonya", EnglishName = "North Macedonia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg" },
                    new Country { Id = 106, Name = "Mali", EnglishName = "Mali", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg" },
                    new Country { Id = 107, Name = "Myanmar (Burma)", EnglishName = "Myanmar (Burma)", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg" },
                    new Country { Id = 108, Name = "Moğolistan", EnglishName = "Mongolia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg" },
                    new Country { Id = 109, Name = "Macao", EnglishName = "Macao", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg" },
                    new Country { Id = 110, Name = "Kuzey Mariana Adaları", EnglishName = "Northern Mariana Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg" },
                    new Country { Id = 111, Name = "Martinique", EnglishName = "Martinique", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg" },
                    new Country { Id = 112, Name = "Moritanya", EnglishName = "Mauritania", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg" },
                    new Country { Id = 113, Name = "Montserrat", EnglishName = "Montserrat", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg" },
                    new Country { Id = 114, Name = "Malta", EnglishName = "Malta", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg" },
                    new Country { Id = 115, Name = "Mauritius", EnglishName = "Mauritius", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg" },
                    new Country { Id = 116, Name = "Maldivler", EnglishName = "Maldives", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg" },
                    new Country { Id = 117, Name = "Malavi", EnglishName = "Malawi", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg" },
                    new Country { Id = 118, Name = "Meksika", EnglishName = "Mexico", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg" },
                    new Country { Id = 119, Name = "Malezya", EnglishName = "Malaysia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg" },
                    new Country { Id = 120, Name = "Mozambik", EnglishName = "Mozambique", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg" },
                    new Country { Id = 121, Name = "Namibya", EnglishName = "Namibia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg" },
                    new Country { Id = 122, Name = "Yeni Kaledonya", EnglishName = "New Caledonia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg" },
                    new Country { Id = 123, Name = "Nijer", EnglishName = "Niger", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg" },
                    new Country { Id = 124, Name = "Norfolk Adası", EnglishName = "Norfolk Island", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg" },
                    new Country { Id = 125, Name = "Nijerya", EnglishName = "Nigeria", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg" },
                    new Country { Id = 126, Name = "Nikaragua", EnglishName = "Nicaragua", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg" },
                    new Country { Id = 127, Name = "Hollanda", EnglishName = "Netherlands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg" },
                    new Country { Id = 128, Name = "Norveç", EnglishName = "Norway", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg" },
                    new Country { Id = 129, Name = "Nepal", EnglishName = "Nepal", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg" },
                    new Country { Id = 130, Name = "Nauru", EnglishName = "Nauru", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg" },
                    new Country { Id = 131, Name = "Niue", EnglishName = "Niue", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg" },
                    new Country { Id = 132, Name = "Yeni Zelanda", EnglishName = "New Zealand", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg" },
                    new Country { Id = 133, Name = "Umman", EnglishName = "Oman", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg" },
                    new Country { Id = 134, Name = "Panama", EnglishName = "Panama", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg" },
                    new Country { Id = 135, Name = "Peru", EnglishName = "Peru", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg" },
                    new Country { Id = 136, Name = "Fransız Polinezyası", EnglishName = "French Polynesia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg" },
                    new Country { Id = 137, Name = "Papua Yeni Gine", EnglishName = "Papua New Guinea", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg" },
                    new Country { Id = 138, Name = "Filipinler", EnglishName = "Philippines", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg" },
                    new Country { Id = 139, Name = "Pakistan", EnglishName = "Pakistan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg" },
                    new Country { Id = 140, Name = "Polonya", EnglishName = "Poland", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg" },
                    new Country { Id = 141, Name = "Saint Pierre ve Miquelon", EnglishName = "Saint Pierre and Miquelon", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg" },
                    new Country { Id = 142, Name = "Pitcairn Adaları", EnglishName = "Pitcairn Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg" },
                    new Country { Id = 143, Name = "Porto Riko", EnglishName = "Puerto Rico", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg" },
                    new Country { Id = 144, Name = "Filistin Bölgesi", EnglishName = "Palestinian Territories", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg" },
                    new Country { Id = 145, Name = "Portekiz", EnglishName = "Portugal", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg" },
                    new Country { Id = 146, Name = "Palau", EnglishName = "Palau", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg" },
                    new Country { Id = 147, Name = "Paraguay", EnglishName = "Paraguay", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg" },
                    new Country { Id = 148, Name = "Katar", EnglishName = "Qatar", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg" },
                    new Country { Id = 149, Name = "Reunion", EnglishName = "Réunion", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg" },
                    new Country { Id = 150, Name = "Romanya", EnglishName = "Romania", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg" },
                    new Country { Id = 151, Name = "Sırbistan", EnglishName = "Serbia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg" },
                    new Country { Id = 152, Name = "Rusya", EnglishName = "Russia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg" },
                    new Country { Id = 153, Name = "Ruanda", EnglishName = "Rwanda", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg" },
                    new Country { Id = 154, Name = "Suudi Arabistan", EnglishName = "Saudi Arabia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg" },
                    new Country { Id = 155, Name = "Solomon Adaları", EnglishName = "Solomon Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg" },
                    new Country { Id = 156, Name = "Seyşeller", EnglishName = "Seychelles", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg" },
                    new Country { Id = 157, Name = "Sudan", EnglishName = "Sudan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg" },
                    new Country { Id = 158, Name = "İsveç", EnglishName = "Sweden", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg" },
                    new Country { Id = 159, Name = "Singapur", EnglishName = "Singapore", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg" },
                    new Country { Id = 160, Name = "Saint Helena", EnglishName = "Saint Helena", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg" },
                    new Country { Id = 161, Name = "Slovenya", EnglishName = "Slovenia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg" },
                    new Country { Id = 162, Name = "Svalbard ve Jan Mayen", EnglishName = "Svalbard and Jan Mayen", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg" },
                    new Country { Id = 163, Name = "Slovakya", EnglishName = "Slovakia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg" },
                    new Country { Id = 164, Name = "Sierra Leone", EnglishName = "Sierra Leone", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg" },
                    new Country { Id = 165, Name = "San Marino", EnglishName = "San Marino", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg" },
                    new Country { Id = 166, Name = "Senegal", EnglishName = "Senegal", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg" },
                    new Country { Id = 167, Name = "Somali", EnglishName = "Somalia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg" },
                    new Country { Id = 168, Name = "Surinam", EnglishName = "Suriname", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg" },
                    new Country { Id = 169, Name = "Güney Sudan", EnglishName = "South Sudan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg" },
                    new Country { Id = 170, Name = "São Tomé ve Príncipe", EnglishName = "São Tomé and Príncipe", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg" },
                    new Country { Id = 171, Name = "El Salvador", EnglishName = "El Salvador", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg" },
                    new Country { Id = 172, Name = "Sint Maarten", EnglishName = "Sint Maarten", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg" },
                    new Country { Id = 173, Name = "Suriye", EnglishName = "Syria", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg" },
                    new Country { Id = 174, Name = "Esvatini", EnglishName = "Eswatini", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg" },
                    new Country { Id = 175, Name = "Tristan da Cunha", EnglishName = "Tristan da Cunha", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TA.svg" },
                    new Country { Id = 176, Name = "Türkmenistan", EnglishName = "Turkmenistan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg" },
                    new Country { Id = 177, Name = "Tunus", EnglishName = "Tunisia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg" },
                    new Country { Id = 178, Name = "Tonga", EnglishName = "Tonga", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg" },
                    new Country { Id = 179, Name = "Doğu Timor", EnglishName = "Timor-Leste", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg" },
                    new Country { Id = 180, Name = "Trinidad ve Tobago", EnglishName = "Trinidad and Tobago", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg" },
                    new Country { Id = 181, Name = "Türkiye", EnglishName = "Turkey", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg" },
                    new Country { Id = 182, Name = "Tuvalu", EnglishName = "Tuvalu", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg" },
                    new Country { Id = 183, Name = "Tayvan", EnglishName = "Taiwan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg" },
                    new Country { Id = 184, Name = "Tanzanya", EnglishName = "Tanzania", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg" },
                    new Country { Id = 185, Name = "Ukrayna", EnglishName = "Ukraine", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg" },
                    new Country { Id = 186, Name = "Uganda", EnglishName = "Uganda", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg" },
                    new Country { Id = 187, Name = "Birleşik Krallık", EnglishName = "United Kingdom", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg" },
                    new Country { Id = 188, Name = "Amerika Birleşik Devletleri", EnglishName = "United States", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg" },
                    new Country { Id = 189, Name = "Uruguay", EnglishName = "Uruguay", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg" },
                    new Country { Id = 190, Name = "Özbekistan", EnglishName = "Uzbekistan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg" },
                    new Country { Id = 191, Name = "Vatikan", EnglishName = "Vatican City", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg" },
                    new Country { Id = 192, Name = "Saint Vincent ve Grenadinler", EnglishName = "Saint Vincent and the Grenadines", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg" },
                    new Country { Id = 193, Name = "Venezuela", EnglishName = "Venezuela", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg" },
                    new Country { Id = 194, Name = "Britanya Virjin Adaları", EnglishName = "British Virgin Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VG.svg" },
                    new Country { Id = 195, Name = "Amerika Virjin Adaları", EnglishName = "U.S. Virgin Islands", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg" },
                    new Country { Id = 196, Name = "Vietnam", EnglishName = "Vietnam", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg" },
                    new Country { Id = 197, Name = "Vanuatu", EnglishName = "Vanuatu", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg" },
                    new Country { Id = 198, Name = "Wallis ve Futuna", EnglishName = "Wallis and Futuna", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg" },
                    new Country { Id = 199, Name = "Samoa", EnglishName = "Samoa", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg" },
                    new Country { Id = 200, Name = "Yemen", EnglishName = "Yemen", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg" },
                    new Country { Id = 201, Name = "Mayotte", EnglishName = "Mayotte", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg" },
                    new Country { Id = 202, Name = "Güney Afrika", EnglishName = "South Africa", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg" },
                    new Country { Id = 203, Name = "Zambia", EnglishName = "Zambia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg" },
                    new Country { Id = 204, Name = "Zimbabve", EnglishName = "Zimbabwe", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg" },
                    new Country { Id = 205, Name = "İngiltere", EnglishName = "England", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ENGLAND.svg" },
                    new Country { Id = 206, Name = "İskoçya", EnglishName = "Scotland", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SCOTLAND.svg" },
                    new Country { Id = 207, Name = "Galler", EnglishName = "Wales", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WALES.svg" },
                    new Country { Id = 208, Name = "İspanya", EnglishName = "Spain", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ES.svg" },
                    new Country { Id = 209, Name = "Belarus", EnglishName = "Belarus", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg" },
                    new Country { Id = 210, Name = "İsrail", EnglishName = "Israel", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IL.svg" },
                    new Country { Id = 211, Name = "Tacikistan", EnglishName = "Tajikistan", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TJ.svg" },
                    new Country { Id = 212, Name = "Fransa", EnglishName = "France", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/FR.svg" },
                    new Country { Id = 213, Name = "Hırvatistan", EnglishName = "Croatia", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HR.svg" },
                    new Country { Id = 214, Name = "Macaristan", EnglishName = "Hungary", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/HU.svg" },
                    new Country { Id = 215, Name = "Tayland", EnglishName = "Thailand", ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TH.svg" }
                    );
        }
    }
}

