// <auto-generated />
using System;
using HantahaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HantahaAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HantahaAPI.Core.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EnglishName = "Ascension Island",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AC.svg",
                            Name = "Ascension Adası"
                        },
                        new
                        {
                            Id = 2,
                            EnglishName = "Andorra",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AD.svg",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 3,
                            EnglishName = "United Arab Emirates",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AE.svg",
                            Name = "Birleşik Arap Emirlikleri"
                        },
                        new
                        {
                            Id = 4,
                            EnglishName = "Afghanistan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg",
                            Name = "Afganistan"
                        },
                        new
                        {
                            Id = 5,
                            EnglishName = "Antigua & Barbuda",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AG.svg",
                            Name = "Antigua ve Barbuda"
                        },
                        new
                        {
                            Id = 6,
                            EnglishName = "Anguilla",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AI.svg",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 7,
                            EnglishName = "Albania",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AL.svg",
                            Name = "Arnavutluk"
                        },
                        new
                        {
                            Id = 8,
                            EnglishName = "Armenia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AM.svg",
                            Name = "Ermenistan"
                        },
                        new
                        {
                            Id = 9,
                            EnglishName = "Angola",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AO.svg",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 10,
                            EnglishName = "Antarctica",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AQ.svg",
                            Name = "Antarktika"
                        },
                        new
                        {
                            Id = 11,
                            EnglishName = "Argentina",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AR.svg",
                            Name = "Arjantin"
                        },
                        new
                        {
                            Id = 12,
                            EnglishName = "American Samoa",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AS.svg",
                            Name = "Amerikan Samoası"
                        },
                        new
                        {
                            Id = 13,
                            EnglishName = "Austria",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AT.svg",
                            Name = "Avusturya"
                        },
                        new
                        {
                            Id = 14,
                            EnglishName = "Australia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AU.svg",
                            Name = "Avustralya"
                        },
                        new
                        {
                            Id = 15,
                            EnglishName = "Aruba",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AW.svg",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 16,
                            EnglishName = "Åland Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AX.svg",
                            Name = "Åland Adaları"
                        },
                        new
                        {
                            Id = 17,
                            EnglishName = "Azerbaijan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AZ.svg",
                            Name = "Azerbaycan"
                        },
                        new
                        {
                            Id = 18,
                            EnglishName = "Bosnia & Herzegovina",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BA.svg",
                            Name = "Bosna-Hersek"
                        },
                        new
                        {
                            Id = 19,
                            EnglishName = "Barbados",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BB.svg",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 20,
                            EnglishName = "Bangladesh",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BD.svg",
                            Name = "Bangladeş"
                        },
                        new
                        {
                            Id = 21,
                            EnglishName = "Belgium",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BE.svg",
                            Name = "Belçika"
                        },
                        new
                        {
                            Id = 22,
                            EnglishName = "Burkina Faso",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BF.svg",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 23,
                            EnglishName = "Bulgaria",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BG.svg",
                            Name = "Bulgaristan"
                        },
                        new
                        {
                            Id = 24,
                            EnglishName = "Bahrain",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BH.svg",
                            Name = "Bahreyn"
                        },
                        new
                        {
                            Id = 25,
                            EnglishName = "Burundi",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BI.svg",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 26,
                            EnglishName = "Benin",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BJ.svg",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 27,
                            EnglishName = "St. Barthélemy",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BL.svg",
                            Name = "St. Barthélemy"
                        },
                        new
                        {
                            Id = 28,
                            EnglishName = "Bermuda",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BM.svg",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 29,
                            EnglishName = "Brunei",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BN.svg",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 30,
                            EnglishName = "Bolivia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BO.svg",
                            Name = "Bolivya"
                        },
                        new
                        {
                            Id = 31,
                            EnglishName = "Caribbean Netherlands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BQ.svg",
                            Name = "Karayip Hollanda"
                        },
                        new
                        {
                            Id = 32,
                            EnglishName = "Brazil",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg",
                            Name = "Brezilya"
                        },
                        new
                        {
                            Id = 33,
                            EnglishName = "Bahamas",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BS.svg",
                            Name = "Bahamalar"
                        },
                        new
                        {
                            Id = 34,
                            EnglishName = "Bhutan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BT.svg",
                            Name = "Butan"
                        },
                        new
                        {
                            Id = 35,
                            EnglishName = "Botswana",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BW.svg",
                            Name = "Botsvana"
                        },
                        new
                        {
                            Id = 36,
                            EnglishName = "Belarus",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BY.svg",
                            Name = "Beyaz Rusya"
                        },
                        new
                        {
                            Id = 37,
                            EnglishName = "Belize",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BZ.svg",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 38,
                            EnglishName = "Canada",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CA.svg",
                            Name = "Kanada"
                        },
                        new
                        {
                            Id = 39,
                            EnglishName = "Cocos (Keeling) Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CC.svg",
                            Name = "Cocos (Keeling) Adaları"
                        },
                        new
                        {
                            Id = 40,
                            EnglishName = "Congo - Kinshasa",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CD.svg",
                            Name = "Kongo - Kinshasa"
                        },
                        new
                        {
                            Id = 41,
                            EnglishName = "Central African Republic",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CF.svg",
                            Name = "Orta Afrika Cumhuriyeti"
                        },
                        new
                        {
                            Id = 42,
                            EnglishName = "Congo - Brazzaville",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CG.svg",
                            Name = "Kongo - Brazzaville"
                        },
                        new
                        {
                            Id = 43,
                            EnglishName = "Switzerland",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CH.svg",
                            Name = "İsviçre"
                        },
                        new
                        {
                            Id = 44,
                            EnglishName = "Côte d’Ivoire",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CI.svg",
                            Name = "Fildişi Sahili"
                        },
                        new
                        {
                            Id = 45,
                            EnglishName = "Cook Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CK.svg",
                            Name = "Cook Adaları"
                        },
                        new
                        {
                            Id = 46,
                            EnglishName = "Chile",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CL.svg",
                            Name = "Şili"
                        },
                        new
                        {
                            Id = 47,
                            EnglishName = "Cameroon",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CM.svg",
                            Name = "Kamerun"
                        },
                        new
                        {
                            Id = 48,
                            EnglishName = "China",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CN.svg",
                            Name = "Çin"
                        },
                        new
                        {
                            Id = 49,
                            EnglishName = "Colombia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CO.svg",
                            Name = "Kolombiya"
                        },
                        new
                        {
                            Id = 50,
                            EnglishName = "Costa Rica",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CR.svg",
                            Name = "Kosta Rika"
                        },
                        new
                        {
                            Id = 51,
                            EnglishName = "Cuba",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CU.svg",
                            Name = "Küba"
                        },
                        new
                        {
                            Id = 52,
                            EnglishName = "Cape Verde",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CV.svg",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 53,
                            EnglishName = "Curaçao",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CW.svg",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 54,
                            EnglishName = "Christmas Island",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CX.svg",
                            Name = "Christmas Adası"
                        },
                        new
                        {
                            Id = 55,
                            EnglishName = "Cyprus",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CY.svg",
                            Name = "Kıbrıs"
                        },
                        new
                        {
                            Id = 56,
                            EnglishName = "Czechia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/CZ.svg",
                            Name = "Çekya"
                        },
                        new
                        {
                            Id = 57,
                            EnglishName = "Germany",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DE.svg",
                            Name = "Almanya"
                        },
                        new
                        {
                            Id = 58,
                            EnglishName = "Djibouti",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DJ.svg",
                            Name = "Cibuti"
                        },
                        new
                        {
                            Id = 59,
                            EnglishName = "Dominica",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DM.svg",
                            Name = "Dominika"
                        },
                        new
                        {
                            Id = 60,
                            EnglishName = "Dominican Republic",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DO.svg",
                            Name = "Dominik Cumhuriyeti"
                        },
                        new
                        {
                            Id = 61,
                            EnglishName = "Algeria",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/DZ.svg",
                            Name = "Cezayir"
                        },
                        new
                        {
                            Id = 62,
                            EnglishName = "Ecuador",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EC.svg",
                            Name = "Ekvador"
                        },
                        new
                        {
                            Id = 63,
                            EnglishName = "Egypt",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EG.svg",
                            Name = "Mısır"
                        },
                        new
                        {
                            Id = 64,
                            EnglishName = "Western Sahara",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/EH.svg",
                            Name = "Batı Sahra"
                        },
                        new
                        {
                            Id = 65,
                            EnglishName = "Eritrea",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ER.svg",
                            Name = "Eritre"
                        },
                        new
                        {
                            Id = 66,
                            EnglishName = "Indonesia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ID.svg",
                            Name = "Endonezya"
                        },
                        new
                        {
                            Id = 67,
                            EnglishName = "Afghanistan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/AF.svg",
                            Name = "Afganistan"
                        },
                        new
                        {
                            Id = 68,
                            EnglishName = "India",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IN.svg",
                            Name = "Hindistan"
                        },
                        new
                        {
                            Id = 69,
                            EnglishName = "Brazil",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/BR.svg",
                            Name = "Brezilya"
                        },
                        new
                        {
                            Id = 70,
                            EnglishName = "Iran",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IR.svg",
                            Name = "İran"
                        },
                        new
                        {
                            Id = 71,
                            EnglishName = "Iraq",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IQ.svg",
                            Name = "Irak"
                        },
                        new
                        {
                            Id = 72,
                            EnglishName = "Ireland",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IE.svg",
                            Name = "İrlanda"
                        },
                        new
                        {
                            Id = 73,
                            EnglishName = "Isle of Man",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IM.svg",
                            Name = "Man Adası"
                        },
                        new
                        {
                            Id = 74,
                            EnglishName = "Iceland",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IS.svg",
                            Name = "İzlanda"
                        },
                        new
                        {
                            Id = 75,
                            EnglishName = "Italy",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/IT.svg",
                            Name = "Italya"
                        },
                        new
                        {
                            Id = 76,
                            EnglishName = "Jersey",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JE.svg",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 77,
                            EnglishName = "Jamaica",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JM.svg",
                            Name = "Jamaika"
                        },
                        new
                        {
                            Id = 78,
                            EnglishName = "Jordan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JO.svg",
                            Name = "Ürdün"
                        },
                        new
                        {
                            Id = 79,
                            EnglishName = "Japan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/JP.svg",
                            Name = "Japonya"
                        },
                        new
                        {
                            Id = 80,
                            EnglishName = "Kenya",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KE.svg",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 81,
                            EnglishName = "Kyrgyzstan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KG.svg",
                            Name = "Kırgızistan"
                        },
                        new
                        {
                            Id = 82,
                            EnglishName = "Cambodia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KH.svg",
                            Name = "Kamboçya"
                        },
                        new
                        {
                            Id = 83,
                            EnglishName = "Kiribati",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KI.svg",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 84,
                            EnglishName = "Comoros",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KM.svg",
                            Name = "Komorlar"
                        },
                        new
                        {
                            Id = 85,
                            EnglishName = "Saint Kitts and Nevis",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KN.svg",
                            Name = "Saint Kitts ve Nevis"
                        },
                        new
                        {
                            Id = 86,
                            EnglishName = "North Korea",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KP.svg",
                            Name = "Kuzey Kore"
                        },
                        new
                        {
                            Id = 87,
                            EnglishName = "South Korea",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KR.svg",
                            Name = "Güney Kore"
                        },
                        new
                        {
                            Id = 88,
                            EnglishName = "Kuwait",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KW.svg",
                            Name = "Kuveyt"
                        },
                        new
                        {
                            Id = 89,
                            EnglishName = "Kazakhstan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/KZ.svg",
                            Name = "Kazakistan"
                        },
                        new
                        {
                            Id = 90,
                            EnglishName = "Laos",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LA.svg",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 91,
                            EnglishName = "Lebanon",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LB.svg",
                            Name = "Lübnan"
                        },
                        new
                        {
                            Id = 92,
                            EnglishName = "Saint Lucia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LC.svg",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 93,
                            EnglishName = "Liechtenstein",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LI.svg",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 94,
                            EnglishName = "Sri Lanka",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LK.svg",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 95,
                            EnglishName = "Liberia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LR.svg",
                            Name = "Liberya"
                        },
                        new
                        {
                            Id = 96,
                            EnglishName = "Lesotho",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LS.svg",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 97,
                            EnglishName = "Lithuania",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LT.svg",
                            Name = "Litvanya"
                        },
                        new
                        {
                            Id = 98,
                            EnglishName = "Luxembourg",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LU.svg",
                            Name = "Lüksemburg"
                        },
                        new
                        {
                            Id = 99,
                            EnglishName = "Latvia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LV.svg",
                            Name = "Letonya"
                        },
                        new
                        {
                            Id = 100,
                            EnglishName = "Libya",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/LY.svg",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 101,
                            EnglishName = "Morocco",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MA.svg",
                            Name = "Fas"
                        },
                        new
                        {
                            Id = 102,
                            EnglishName = "Monaco",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MC.svg",
                            Name = "Monako"
                        },
                        new
                        {
                            Id = 103,
                            EnglishName = "Moldova",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MD.svg",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 104,
                            EnglishName = "Montenegro",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ME.svg",
                            Name = "Karadağ"
                        },
                        new
                        {
                            Id = 105,
                            EnglishName = "Madagascar",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MG.svg",
                            Name = "Madagaskar"
                        },
                        new
                        {
                            Id = 106,
                            EnglishName = "Marshall Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MH.svg",
                            Name = "Marshall Adaları"
                        },
                        new
                        {
                            Id = 107,
                            EnglishName = "North Macedonia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MK.svg",
                            Name = "Makedonya"
                        },
                        new
                        {
                            Id = 108,
                            EnglishName = "Mali",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ML.svg",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 109,
                            EnglishName = "Myanmar (Burma)",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MM.svg",
                            Name = "Myanmar (Burma)"
                        },
                        new
                        {
                            Id = 110,
                            EnglishName = "Mongolia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MN.svg",
                            Name = "Moğolistan"
                        },
                        new
                        {
                            Id = 111,
                            EnglishName = "Macao",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MO.svg",
                            Name = "Macao"
                        },
                        new
                        {
                            Id = 112,
                            EnglishName = "Northern Mariana Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MP.svg",
                            Name = "Kuzey Mariana Adaları"
                        },
                        new
                        {
                            Id = 113,
                            EnglishName = "Martinique",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MQ.svg",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 114,
                            EnglishName = "Mauritania",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MR.svg",
                            Name = "Moritanya"
                        },
                        new
                        {
                            Id = 115,
                            EnglishName = "Montserrat",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MS.svg",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 116,
                            EnglishName = "Malta",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MT.svg",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 117,
                            EnglishName = "Mauritius",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MU.svg",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 118,
                            EnglishName = "Maldives",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MV.svg",
                            Name = "Maldivler"
                        },
                        new
                        {
                            Id = 119,
                            EnglishName = "Malawi",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MW.svg",
                            Name = "Malavi"
                        },
                        new
                        {
                            Id = 120,
                            EnglishName = "Mexico",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MX.svg",
                            Name = "Meksika"
                        },
                        new
                        {
                            Id = 121,
                            EnglishName = "Malaysia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MY.svg",
                            Name = "Malezya"
                        },
                        new
                        {
                            Id = 122,
                            EnglishName = "Mozambique",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/MZ.svg",
                            Name = "Mozambik"
                        },
                        new
                        {
                            Id = 123,
                            EnglishName = "Namibia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NA.svg",
                            Name = "Namibya"
                        },
                        new
                        {
                            Id = 124,
                            EnglishName = "New Caledonia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NC.svg",
                            Name = "Yeni Kaledonya"
                        },
                        new
                        {
                            Id = 125,
                            EnglishName = "Niger",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NE.svg",
                            Name = "Nijer"
                        },
                        new
                        {
                            Id = 126,
                            EnglishName = "Norfolk Island",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NF.svg",
                            Name = "Norfolk Adası"
                        },
                        new
                        {
                            Id = 127,
                            EnglishName = "Nigeria",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NG.svg",
                            Name = "Nijerya"
                        },
                        new
                        {
                            Id = 128,
                            EnglishName = "Nicaragua",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NI.svg",
                            Name = "Nikaragua"
                        },
                        new
                        {
                            Id = 129,
                            EnglishName = "Netherlands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NL.svg",
                            Name = "Hollanda"
                        },
                        new
                        {
                            Id = 130,
                            EnglishName = "Norway",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NO.svg",
                            Name = "Norveç"
                        },
                        new
                        {
                            Id = 131,
                            EnglishName = "Nepal",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NP.svg",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 132,
                            EnglishName = "Nauru",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NR.svg",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 133,
                            EnglishName = "Niue",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NU.svg",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 134,
                            EnglishName = "New Zealand",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/NZ.svg",
                            Name = "Yeni Zelanda"
                        },
                        new
                        {
                            Id = 135,
                            EnglishName = "Oman",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/OM.svg",
                            Name = "Umman"
                        },
                        new
                        {
                            Id = 136,
                            EnglishName = "Panama",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PA.svg",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 137,
                            EnglishName = "Peru",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PE.svg",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 138,
                            EnglishName = "French Polynesia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PF.svg",
                            Name = "Fransız Polinezyası"
                        },
                        new
                        {
                            Id = 139,
                            EnglishName = "Papua New Guinea",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PG.svg",
                            Name = "Papua Yeni Gine"
                        },
                        new
                        {
                            Id = 140,
                            EnglishName = "Philippines",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PH.svg",
                            Name = "Filipinler"
                        },
                        new
                        {
                            Id = 141,
                            EnglishName = "Pakistan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PK.svg",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 142,
                            EnglishName = "Poland",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PL.svg",
                            Name = "Polonya"
                        },
                        new
                        {
                            Id = 143,
                            EnglishName = "Saint Pierre and Miquelon",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PM.svg",
                            Name = "Saint Pierre ve Miquelon"
                        },
                        new
                        {
                            Id = 144,
                            EnglishName = "Pitcairn Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PN.svg",
                            Name = "Pitcairn Adaları"
                        },
                        new
                        {
                            Id = 145,
                            EnglishName = "Puerto Rico",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PR.svg",
                            Name = "Porto Riko"
                        },
                        new
                        {
                            Id = 146,
                            EnglishName = "Palestinian Territories",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PS.svg",
                            Name = "Filistin Bölgesi"
                        },
                        new
                        {
                            Id = 147,
                            EnglishName = "Portugal",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PT.svg",
                            Name = "Portekiz"
                        },
                        new
                        {
                            Id = 148,
                            EnglishName = "Palau",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PW.svg",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 149,
                            EnglishName = "Paraguay",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/PY.svg",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 150,
                            EnglishName = "Qatar",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/QA.svg",
                            Name = "Katar"
                        },
                        new
                        {
                            Id = 151,
                            EnglishName = "Réunion",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RE.svg",
                            Name = "Reunion"
                        },
                        new
                        {
                            Id = 152,
                            EnglishName = "Romania",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RO.svg",
                            Name = "Romanya"
                        },
                        new
                        {
                            Id = 153,
                            EnglishName = "Serbia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RS.svg",
                            Name = "Sırbistan"
                        },
                        new
                        {
                            Id = 154,
                            EnglishName = "Russia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RU.svg",
                            Name = "Rusya"
                        },
                        new
                        {
                            Id = 155,
                            EnglishName = "Rwanda",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/RW.svg",
                            Name = "Ruanda"
                        },
                        new
                        {
                            Id = 156,
                            EnglishName = "Saudi Arabia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SA.svg",
                            Name = "Suudi Arabistan"
                        },
                        new
                        {
                            Id = 157,
                            EnglishName = "Solomon Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SB.svg",
                            Name = "Solomon Adaları"
                        },
                        new
                        {
                            Id = 158,
                            EnglishName = "Seychelles",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SC.svg",
                            Name = "Seyşeller"
                        },
                        new
                        {
                            Id = 159,
                            EnglishName = "Sudan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SD.svg",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 160,
                            EnglishName = "Sweden",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SE.svg",
                            Name = "İsveç"
                        },
                        new
                        {
                            Id = 161,
                            EnglishName = "Singapore",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SG.svg",
                            Name = "Singapur"
                        },
                        new
                        {
                            Id = 162,
                            EnglishName = "Saint Helena",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SH.svg",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Id = 163,
                            EnglishName = "Slovenia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SI.svg",
                            Name = "Slovenya"
                        },
                        new
                        {
                            Id = 164,
                            EnglishName = "Svalbard and Jan Mayen",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SJ.svg",
                            Name = "Svalbard ve Jan Mayen"
                        },
                        new
                        {
                            Id = 165,
                            EnglishName = "Slovakia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SK.svg",
                            Name = "Slovakya"
                        },
                        new
                        {
                            Id = 166,
                            EnglishName = "Sierra Leone",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SL.svg",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 167,
                            EnglishName = "San Marino",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SM.svg",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 168,
                            EnglishName = "Senegal",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SN.svg",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 169,
                            EnglishName = "Somalia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SO.svg",
                            Name = "Somali"
                        },
                        new
                        {
                            Id = 170,
                            EnglishName = "Suriname",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SR.svg",
                            Name = "Surinam"
                        },
                        new
                        {
                            Id = 171,
                            EnglishName = "South Sudan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SS.svg",
                            Name = "Güney Sudan"
                        },
                        new
                        {
                            Id = 172,
                            EnglishName = "São Tomé and Príncipe",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ST.svg",
                            Name = "São Tomé ve Príncipe"
                        },
                        new
                        {
                            Id = 173,
                            EnglishName = "El Salvador",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SV.svg",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 174,
                            EnglishName = "Sint Maarten",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SX.svg",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 175,
                            EnglishName = "Syria",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SY.svg",
                            Name = "Suriye"
                        },
                        new
                        {
                            Id = 176,
                            EnglishName = "Eswatini",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SZ.svg",
                            Name = "Esvatini"
                        },
                        new
                        {
                            Id = 177,
                            EnglishName = "Tristan da Cunha",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TA.svg",
                            Name = "Tristan da Cunha"
                        },
                        new
                        {
                            Id = 178,
                            EnglishName = "Turkmenistan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TM.svg",
                            Name = "Türkmenistan"
                        },
                        new
                        {
                            Id = 179,
                            EnglishName = "Tunisia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TN.svg",
                            Name = "Tunus"
                        },
                        new
                        {
                            Id = 180,
                            EnglishName = "Tonga",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TO.svg",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 181,
                            EnglishName = "Timor-Leste",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TL.svg",
                            Name = "Doğu Timor"
                        },
                        new
                        {
                            Id = 182,
                            EnglishName = "Trinidad and Tobago",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TT.svg",
                            Name = "Trinidad ve Tobago"
                        },
                        new
                        {
                            Id = 183,
                            EnglishName = "Turkey",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TR.svg",
                            Name = "Türkiye"
                        },
                        new
                        {
                            Id = 184,
                            EnglishName = "Tuvalu",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TV.svg",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 185,
                            EnglishName = "Taiwan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TW.svg",
                            Name = "Tayvan"
                        },
                        new
                        {
                            Id = 186,
                            EnglishName = "Tanzania",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/TZ.svg",
                            Name = "Tanzanya"
                        },
                        new
                        {
                            Id = 187,
                            EnglishName = "Ukraine",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UA.svg",
                            Name = "Ukrayna"
                        },
                        new
                        {
                            Id = 188,
                            EnglishName = "Uganda",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UG.svg",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 189,
                            EnglishName = "United Kingdom",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/GB.svg",
                            Name = "Birleşik Krallık"
                        },
                        new
                        {
                            Id = 190,
                            EnglishName = "United States",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/US.svg",
                            Name = "Amerika Birleşik Devletleri"
                        },
                        new
                        {
                            Id = 191,
                            EnglishName = "Uruguay",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UY.svg",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 192,
                            EnglishName = "Uzbekistan",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/UZ.svg",
                            Name = "Özbekistan"
                        },
                        new
                        {
                            Id = 193,
                            EnglishName = "Vatican City",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VA.svg",
                            Name = "Vatikan"
                        },
                        new
                        {
                            Id = 194,
                            EnglishName = "Saint Vincent and the Grenadines",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VC.svg",
                            Name = "Saint Vincent ve Grenadinler"
                        },
                        new
                        {
                            Id = 195,
                            EnglishName = "Venezuela",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VE.svg",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 196,
                            EnglishName = "British Virgin Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VG.svg",
                            Name = "Britanya Virjin Adaları"
                        },
                        new
                        {
                            Id = 197,
                            EnglishName = "U.S. Virgin Islands",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VI.svg",
                            Name = "Amerika Virjin Adaları"
                        },
                        new
                        {
                            Id = 198,
                            EnglishName = "Vietnam",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VN.svg",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 199,
                            EnglishName = "Vanuatu",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/VU.svg",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 200,
                            EnglishName = "Wallis and Futuna",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WF.svg",
                            Name = "Wallis ve Futuna"
                        },
                        new
                        {
                            Id = 201,
                            EnglishName = "Samoa",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WS.svg",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 202,
                            EnglishName = "Yemen",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YE.svg",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 203,
                            EnglishName = "Mayotte",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/YT.svg",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 204,
                            EnglishName = "South Africa",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZA.svg",
                            Name = "Güney Afrika"
                        },
                        new
                        {
                            Id = 205,
                            EnglishName = "Zambia",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZM.svg",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 206,
                            EnglishName = "Zimbabwe",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ZW.svg",
                            Name = "Zimbabve"
                        },
                        new
                        {
                            Id = 207,
                            EnglishName = "England",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/ENGLAND.svg",
                            Name = "İngiltere"
                        },
                        new
                        {
                            Id = 208,
                            EnglishName = "Scotland",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/SCOTLAND.svg",
                            Name = "İskoçya"
                        },
                        new
                        {
                            Id = 209,
                            EnglishName = "Wales",
                            ImageURL = "https://cdn.jsdelivr.net/npm/country-flag-emoji-json@2.0.0/dist/images/WALES.svg",
                            Name = "Galler"
                        });
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.SystemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionSource")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("text");

                    b.Property<string>("ExceptionUrl")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("SystemLog");
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastIV")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserRoleId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole", (string)null);
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.User", b =>
                {
                    b.HasOne("HantahaAPI.Core.Model.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.UserRole", b =>
                {
                    b.HasOne("HantahaAPI.Core.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HantahaAPI.Core.Model.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.Country", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("HantahaAPI.Core.Model.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
